name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy website
      uses: appleboy/ssh-action@v0.1.2
      with: 
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

        script: |
          mkdir andrew
          cd andrew
          sudo git clone https://github.com/anh190/Andrew_Site.git
          rsync -r ~/andrew/Andrew_Site/* /var/www/ucsddev.site/public_html/members/
          echo 'Deployment successful to digital ocean'
